### ISSUE TITLE
Trained model weights

### ISSUE THREAD

**Issue by amalad** [zychen423/KE-VIST#1]
Hi,

Could you please share the weights of the Faster RCNN model trained on the Visual Genome dataset?

Thanks!

**Comment by joe32140** [comment]
Hi @amalad, 

We use the pre-trained weights in this repo https://github.com/peteanderson80/bottom-up-attention#demo . 
Please let us know if you have any other questions!

**Comment by zychen423** [comment]
@amalad 

Seems this issue is solved, so I will close it.
