### ISSUE TITLE
source image of VIST

### ISSUE THREAD

**Issue by Thinking-more** [zychen423/KE-VIST#10]
您好，我想下载原始的VIST的数据集，但是VIST的官网提供的google drive链接已经无法使用。根据json文件中的URL爬取的image有非常多已经损坏了。所以想问一下您是否保存着VIST数据集的原始图片，如果有的话能否分享我一份呀。万分感谢！祝好！

**Comment by joe32140** [comment]
你好，我剛剛測試 google drive 還可以使用，請問是哪個檔案無法下載？ https://visionandlanguage.net/VIST/dataset.html

**Comment by Thinking-more** [comment]
> 你好，我剛剛測試 google drive 還可以使用，請問是哪個檔案無法下載？ https://visionandlanguage.net/VIST/dataset.html

您好，我点击https://visionandlanguage.net/VIST/dataset.html中的下载链接下载，但是Google drive显示没有权限。不知道您是否可以正常下载呀？

**Comment by joe32140** [comment]
對，我可以正常下載，沒有權限的問題。

**Comment by Thinking-more** [comment]
> 對，我可以正常下載，沒有權限的問題。

奇怪，我每次都显示有权限问题，无法下载。不知道您本地有没有保存该数据集呀，如果有的话，能不能分享我一份呀。万分感谢！

**Comment by joe32140** [comment]
We don't have access to the servers now since we have left. Sorry we can not help on that.
