### ISSUE TITLE
Problem in stage 1

### ISSUE THREAD

**Issue by FeatherZhong** [zychen423/KE-VIST#4]
Thank you for sharing the code,
I am trying to reproduce the result of the paper, but I have a problem in the first stage. In the instructions you mentioned using faster RCNN to extract object feature, and I saw you mentioned this [repository](https://github.com/peteanderson80/bottom-up-attention) in another [issue](https://github.com/zychen423/KE-VIST/issues/1). So I tried to extract the features using the lib folder in the repository and the code you provided in [stage 1](https://github.com/zychen423/KE-VIST/tree/master/src/stage1/image_object_detection) and I got the error message because your code is python3 but in lib it's python2.
Can you tell me the details of how to extract features using faster RCNN?
Thanks!

**Comment by joe32140** [comment]
Hi, 
Thank you for your interest in our paper!

Could you provide more details about the error message you got?

**Comment by FeatherZhong** [comment]
Thank you for your prompt reply,
The errors I get look like running a python2 code using python3
`Traceback (most recent call last):
  File "/home/jiangaiwen/KE-VIST/src/stage1/image_object_detection/tools/generate_tsv.py", line 15, in <module>
    from fast_rcnn.test import im_detect,_get_blobs
  File "/home/jiangaiwen/KE-VIST/src/stage1/image_object_detection/tools/../lib/fast_rcnn/test.py", line 222
    print filename
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(filename)?`

The error was in this code [fast_rcnn/test.py](https://github.com/peteanderson80/bottom-up-attention/blob/master/lib/fast_rcnn/test.py#L222)

**Comment by joe32140** [comment]
Did remove parentheses from test.py help? or did just run with python2 work? I might have tried the former. I don't have access to the code base now. I will redirect you to my co-author! He may help me to push the code here.

**Comment by FeatherZhong** [comment]
Yes, I've tried to transfer the code in lib to python3, but there's so much to change that I don't think it's the right way to do it.
I saw in the README that you're using python3.6, and I have not tried to change your code to run python2, because I configured pycaffe to run python3, and configuring Caffe can be a real hassle.If you do use python2 to extract data. I'll try it next.

**Comment by FeatherZhong** [comment]
I solved this problem by runnning on python3 and fixing every python2 errors, after finally configuring Caffe for my Python environment, I successfully ran code to extract image features.
Thank you very much for your help!

**Comment by xinli2008** [comment]
Hi,I have came across the same problems,can you share the Modified code？
And can i have you email for further discussion? @FeatherZhong
