### ISSUE TITLE
Extracted faster rcnn features of VIST

### ISSUE THREAD

**Issue by FeatherZhong** [zychen423/KE-VIST#5]
Thank you again for such an excellent work,
When I used the code to extract VIST image features at stage 1, I found that my GPU 2080Ti did not have enough memory which need 12GB to run the code. I tried to use CPU for calculation, but it took too long, about half a year.
I would really appreciate if you could share the extracted features of VIST.

**Comment by joe32140** [comment]
Hi,

Have you tried running on your gpu? The original repo said you need 12G to **train** the model. I remembered it can run the model with less memory.

**Comment by FeatherZhong** [comment]
Thank you for the response,
Yes, I tried running code on my GPU, and I got the this error message
`Check failed: error == cudaSuccess (2 vs. 0)  out of memory`
I found a [issue](https://github.com/peteanderson80/bottom-up-attention/issues/3) in the original repository that mentioned the need for 12GB of GPU memory was also required for eval.

**Comment by FeatherZhong** [comment]
I try to modify the NCCL setting in cafffe and finnally extract the features using around 10GB memory.
Thank you very much for your help!
