### ISSUE TITLE
problems in stage 1

### ISSUE THREAD

**Issue by xinli2008** [zychen423/KE-VIST#7]
hello,I am trying to reproduce the result of the paper, but I have a problem in the first stage.
here is the detail of the question:
i am trying the code :bash resize_all_image.sh CPU_NUM IMAGE_DIR OUTPUT_DIR ,but i came cross a problem:
Flattening Gigaword with CPU_NUM processes...
resize_all_image.sh: line 10: parallel: command not found
ls: cannot access 'IMAGE_DIR': No such file or directory
i am so sorry to bother you

**Comment by zychen423** [comment]
Hi, shaoniana1997

I believe that you should replace 'CPU_NUM', 'IMAGE_DIR', 'OUTPUT_DIR' with appropriate arguments. 

- CPU_NUM: number of process to run this script
- IMAGE_DIR: path to the directory where you place the images
- OUTPUT_DIR: path to the directory where you expect the output of this script will live in

And I also notice that there is no instruction about how to access to those images, perhaps @ethan5437 could help?

**Comment by zychen423** [comment]
Hi, @shaoniana1997 

I also notice that there is an error `resize_all_image.sh: line 10: parallel: command not found`
maybe you need to execute this first `sudo apt install parallel`

**Comment by shaoniana1997** [comment]
hi,hello,I am trying to reproduce the result of the paper, but I have a problem in the first stage.
here is the detail of the question:
Traceback (most recent call last):
  File "./tools/generate_tsv.py", line 14, in <module>
    from fast_rcnn.config import cfg, cfg_from_file
ModuleNotFoundError: No module named 'fast_rcnn'
when i try to run in src/stage1/image_object_detection perform object detection & object feature extraction With Caffe environment.
can you give me some useful advice ? thank you very much! @zychen423
