### ISSUE TITLE
question in stage1

### ISSUE THREAD

**Issue by xinli2008** [zychen423/KE-VIST#8]
hi,hello,I am trying to reproduce the result of the paper, but I have a problem in the first stage.
here is the detail of the question:
Traceback (most recent call last):
File "./tools/generate_tsv.py", line 14, in
from fast_rcnn.config import cfg, cfg_from_file
ModuleNotFoundError: No module named 'fast_rcnn'
when i try to run in src/stage1/image_object_detection perform object detection & object feature extraction With Caffe environment.
can you give me some useful advice ? thank you very much!

**Comment by joe32140** [comment]
Hi,

Please see details in the original repo https://github.com/peteanderson80/bottom-up-attention . Let me know if you have any questions!
